// 앱 곳곳에 장식으로 배치하고, 레벨업으로 모으는 동물 캐릭터들.
//
// 이미지는 프로젝트에 저장하지 않고 구글 드라이브에서 직접 불러온다.
// (로컬 파일은 배포 위치에 따라 경로가 깨지는 문제가 있었다.)
// drive.google.com/uc?export=view 형식은 CORP(same-site) 헤더 때문에 다른 도메인의
// <img>에서 차단되므로, 제한이 없는 lh3.googleusercontent.com 썸네일 CDN을 쓴다.
// =s400: 가장 긴 변을 400px로 맞춘다. 장식용 작은 이미지라 이 정도면 선명하고 가볍다.
const DRIVE_IDS = {
  frog: '151typ-XjjrHhdAmOsc-60djfZUiTR6DZ',
  chick: '1PhcyhoAKA6xnfQLXnQ1iH-O_ZEUS0rAN',
  fox: '1Z9MphY_VryMMXngXYRR3j90S6gg4921c',
  penguin: '1D6mIbiJCgZb5ava0Sk885iBcAczcvWTV',
  hedgehog: '1eHe6lAmFb79Wxxgzgwkl8CGFY-J8Sdz8',
  raccoon: '16-lxyQXeiernviS0eukSwHhk-YCYeMwy',
  cat: '1xJ_yibwAyT16OMf8_x-FsLg1ZPvg7E63',
  elephant: '1NIVCvzT6sRBZlPlQnvNWkw1uhGnPeVbk',
  blackpenguin: '1iCj_CB6ZMfrXDp9DY1xhrI0EDldRg3Ah',
  sloth: '1eXwrS-9yzGfmzmb-gIHxFWYAzNE4v_sr',
  // 동물의 숲 캐릭터 69마리 (레벨업 컬렉션 확장분, ac01~ac69)
  ac01: '10PKtkvrgtIrrRqslFOFc3bcdmPQrodMG',
  ac02: '1gS2w-kUlgAHYgZvlXGSucUEOAjYs5VgI',
  ac03: '12fY1UZSJwnbe5bI-zad6jjAxde3z28ml',
  ac04: '1e79nYf3jEg5jNQyrzeN5Rh00a1e5YUiz',
  ac05: '1gbrfW5MxAiCLXufPxu0V-umOVx-OlzLm',
  ac06: '14m16tkfsdHcScSD1Fy09q2f1WEl9MPCr',
  ac07: '1JCkzWQ5WC6nIgjt7mO3oVUb9qQSxFgTR',
  ac08: '1TtRzao7XRAzCaubtBnRAYJ1W-64ZDntd',
  ac09: '13j9QlH8maU3-yshQod82lieenSPed-9p',
  ac10: '1Q9Jk23HohZ1oZ9XE_sckxzPoBCCHA9Yb',
  ac11: '1rbKtQ9_sjADGUBbO0ro9cuG5tvlPAGVO',
  ac12: '1zJ68W6MK_zHzhdHIUKRTSGpexqu5Jikl',
  ac13: '1Suw9NgxXM-cey3KBsu68JzFMiGNpMUuX',
  ac14: '1TJ7-5ENdABM_196SsMW4jBr0ZNiWSP0n',
  ac15: '1YGXt0g2j7SOmVireujW0olcCJKwyOtr2',
  ac16: '1qn-BUrxmJHR8Qp_Jdv2u-Bh71IMndiRN',
  ac17: '1aQ5_KzmqRQK6lHHJ_0mnu1CTGXst-PiS',
  ac18: '1clDlrKgUaQPG8rSMJexKN7OFw8u8NYBz',
  ac19: '1dZZtfqLOGh9zePhwLctgWKWG1xqRjrTf',
  ac20: '17c-WgsU9vwMHqBjdJmURc4AhgnMrJ_xl',
  ac21: '1__jttc1PpTeX1bTXp1KXEaJjhKivSzAN',
  ac22: '1b_8FPUxunusVE05y3zY614XEXxTaijpR',
  ac23: '1ip9ZBGuD4zniEhMx3d-u-Kl8HZntu4uJ',
  ac24: '178oiwYz77FU7OKlENW8WBulqB3N8K1vJ',
  ac25: '17JfviYwhvaL9sgz6WhQrlopoEOwu6iPm',
  ac26: '1jy1XrmbTz6MAxQUUj-89TfQ52Q4Ou0EU',
  ac27: '1vHx6Z7CC9pAFSSQ0WnBfhIzMtZsqeran',
  ac28: '1B3SRXirO6e6iCcVFcNlacpo_u_O-Rev2',
  ac29: '1JTrfbt68gENteetKV83DtPfxMzmW6dgK',
  ac30: '1LQTl59CdCI-M3Kuvj7T-5NAlr7MLPpal',
  ac31: '1SZNTfEWpLWzhzDyYEMM05wztut3NtNEm',
  ac32: '1VvtO7ymfk08tZzCDN75_J0r47i9-3CzY',
  ac33: '1_RMbBJUZc2YY7lzlfJYTZadHAwzBh-z1',
  ac34: '1drppmm9GTgpnfOttNH4Z4yURAvOVgXoi',
  ac35: '17TMQ7LoadG3gaCCHh3gtxu3xX7Hk12dk',
  ac36: '1N0oWTPWvbbkHrw2TLt-9p6YRcDzT3ndM',
  ac37: '1n3uIOfiuHUccXp4INYDZz-lyyU5QuhD-',
  ac38: '1tO-FsEpSCwZ4EqQgcZjjmueoMfLllyYm',
  ac39: '1PhqehIfUxg9jpDONx3DyOo12DPn6nr7e',
  ac40: '1TF6bgknHmdynFm7rAKgFyP52-ihUU8o-',
  ac41: '1q7GdoDE2zzpmWWNmzYZHwuLhxQhyfZih',
  ac42: '1uI1ZavcS9kLq74Vz8yg-JlR9hhxY3oa-',
  ac43: '1GlkXm_uOR0sUyQdrze1sMSAkF1E64P2_',
  ac44: '1SPRoTWjPkGqnu9n3Iby5NoQesxOuvTY8',
  ac45: '1WaW6Y62JDc88GDEAFP_WRNElBK32ZWLo',
  ac46: '1fvl_0L6UcTrMsitEgcLym1nzj5GuqY2L',
  ac47: '1i3de2FJXfcEnDFcSVoXE1NdxbJ3MFidI',
  ac48: '1iNKPMYSNVFQiBaqz2x3T8sxjWo3Spo_k',
  ac49: '1rcsl74teE5s5n1o_X8GSrDp13yVRNel2',
  ac50: '1vdjQs1pZBHvmYlqE189TLc8H8ZqvE-pw',
  ac51: '1g0f0QTSvdQnF61tLiVA52bizTWEcpWeu',
  ac52: '1g1V08ClHeMUagtVeiQYeYmk0npYZIeeJ',
  ac53: '1uN1FnJRHuItLTu6EYsbLPU48G3KAobp3',
  ac54: '1zgclxyD3NmNzRh374NX4mZpEH-jTV7DS',
  ac55: '10cHtNbC7WJ-Hqte6oOYQFoF4pKknNuv3',
  ac56: '1XwQ3RL2N0gSPg7acQVx9cCasmMPsJYlr',
  ac57: '1bP2ej7JY34545qPmXCMZRMeoTP0Cbnf9',
  ac58: '1gXeceAQssLmDq701_tCafgdOln3hyVOJ',
  ac59: '1_6v4kkP7glrbZoGgVg32nQeT6seF-Fce',
  ac60: '1f9G6jVus9C1W1JG5L0Zpn4QBBCpDjKai',
  ac61: '1q06F3ACD1aMjbay-yw_IVwUtWGwt4_sM',
  ac62: '1vdkRUn6qxcLlE6rgKWs63XNjfeJreDm5',
  ac63: '1K5VfefzXKc21_6skCGW8_ehAA5D97InM',
  ac64: '1NGW1XIBxytmtm112kt0OHNLdvLoxBqFQ',
  ac65: '1VvpMLjMcfkpI6drx83WsNIszpBCuckDr',
  ac66: '1B__DHPh0wJNf-h4oxKGsoAYJAjEyjGLN',
  ac67: '1MV7avlEF2w1SThK887eUx_kushSXK_Ob',
  ac68: '1sSQoRXGMSipAyjB0XGJA0ZsbH063rSNI',
  ac69: '1CVUvld4y0Sen2QrFn-vuwX081vIWlOoi',
};

function driveImageUrl(id) {
  return `https://lh3.googleusercontent.com/d/${id}=s400`;
}

// naturalWidth/naturalHeight는 원본 PNG의 픽셀 비율이다.
// CharacterMascot가 이 비율로 <img>에 width/height를 지정해, 네트워크로 이미지를
// 불러오기 전에도 정확한 자리를 잡아 레이아웃 밀림(CLS)과 헤더 높이 튐을 막는다.
// label: 아이에게 보여줄 이름. ring/glow: 카드 장식에 쓰는 캐릭터별 색 톤.
export const CHARACTERS = {
  frog: {
    src: driveImageUrl(DRIVE_IDS.frog),
    label: '개구리',
    alt: '개구리 친구',
    naturalWidth: 290,
    naturalHeight: 251,
    ring: 'border-emerald-100',
    glow: 'shadow-emerald-100/60',
  },
  chick: {
    src: driveImageUrl(DRIVE_IDS.chick),
    label: '병아리',
    alt: '병아리 친구',
    naturalWidth: 302,
    naturalHeight: 317,
    ring: 'border-yellow-100',
    glow: 'shadow-yellow-100/60',
  },
  fox: {
    src: driveImageUrl(DRIVE_IDS.fox),
    label: '여우',
    alt: '여우 친구',
    naturalWidth: 339,
    naturalHeight: 290,
    ring: 'border-orange-100',
    glow: 'shadow-orange-100/60',
  },
  penguin: {
    src: driveImageUrl(DRIVE_IDS.penguin),
    label: '갈색 펭귄',
    alt: '갈색 펭귄 친구',
    naturalWidth: 290,
    naturalHeight: 268,
    ring: 'border-stone-200',
    glow: 'shadow-stone-100/60',
  },
  hedgehog: {
    src: driveImageUrl(DRIVE_IDS.hedgehog),
    label: '고슴도치',
    alt: '고슴도치 친구',
    naturalWidth: 307,
    naturalHeight: 285,
    ring: 'border-orange-100',
    glow: 'shadow-orange-100/60',
  },
  raccoon: {
    src: driveImageUrl(DRIVE_IDS.raccoon),
    label: '라쿤',
    alt: '라쿤 친구',
    naturalWidth: 296,
    naturalHeight: 258,
    ring: 'border-slate-200',
    glow: 'shadow-slate-100/60',
  },
  cat: {
    src: driveImageUrl(DRIVE_IDS.cat),
    label: '줄무늬 고양이',
    alt: '줄무늬 고양이 친구',
    naturalWidth: 327,
    naturalHeight: 270,
    ring: 'border-slate-200',
    glow: 'shadow-slate-100/60',
  },
  elephant: {
    src: driveImageUrl(DRIVE_IDS.elephant),
    label: '코끼리',
    alt: '코끼리 친구',
    naturalWidth: 419,
    naturalHeight: 248,
    ring: 'border-amber-100',
    glow: 'shadow-amber-100/60',
  },
  blackpenguin: {
    src: driveImageUrl(DRIVE_IDS.blackpenguin),
    label: '검정 펭귄',
    alt: '검정 펭귄 친구',
    naturalWidth: 315,
    naturalHeight: 241,
    ring: 'border-slate-300',
    glow: 'shadow-slate-200/60',
  },
  sloth: {
    src: driveImageUrl(DRIVE_IDS.sloth),
    label: '나무늘보',
    alt: '나무늘보 친구',
    naturalWidth: 309,
    naturalHeight: 287,
    ring: 'border-amber-200',
    glow: 'shadow-amber-100/60',
  },
  ac01: {
    src: driveImageUrl(DRIVE_IDS.ac01),
    label: '늘봉',
    alt: '늘봉 친구',
    naturalWidth: 400,
    naturalHeight: 400,
    ring: 'border-rose-100',
    glow: 'shadow-rose-100/60',
  },
  ac02: {
    src: driveImageUrl(DRIVE_IDS.ac02),
    label: '고순이',
    alt: '고순이 친구',
    naturalWidth: 400,
    naturalHeight: 400,
    ring: 'border-orange-100',
    glow: 'shadow-orange-100/60',
  },
  ac03: {
    src: driveImageUrl(DRIVE_IDS.ac03),
    label: '부엉',
    alt: '부엉 친구',
    naturalWidth: 400,
    naturalHeight: 400,
    ring: 'border-amber-100',
    glow: 'shadow-amber-100/60',
  },
  ac04: {
    src: driveImageUrl(DRIVE_IDS.ac04),
    label: '펌킹',
    alt: '펌킹 친구',
    naturalWidth: 400,
    naturalHeight: 400,
    ring: 'border-yellow-100',
    glow: 'shadow-yellow-100/60',
  },
  ac05: {
    src: driveImageUrl(DRIVE_IDS.ac05),
    label: '밤돌이',
    alt: '밤돌이 친구',
    naturalWidth: 400,
    naturalHeight: 400,
    ring: 'border-lime-100',
    glow: 'shadow-lime-100/60',
  },
  ac06: {
    src: driveImageUrl(DRIVE_IDS.ac06),
    label: '패트릭',
    alt: '패트릭 친구',
    naturalWidth: 400,
    naturalHeight: 400,
    ring: 'border-emerald-100',
    glow: 'shadow-emerald-100/60',
  },
  ac07: {
    src: driveImageUrl(DRIVE_IDS.ac07),
    label: '고숙이',
    alt: '고숙이 친구',
    naturalWidth: 400,
    naturalHeight: 400,
    ring: 'border-teal-100',
    glow: 'shadow-teal-100/60',
  },
  ac08: {
    src: driveImageUrl(DRIVE_IDS.ac08),
    label: '리사',
    alt: '리사 친구',
    naturalWidth: 400,
    naturalHeight: 400,
    ring: 'border-cyan-100',
    glow: 'shadow-cyan-100/60',
  },
  ac09: {
    src: driveImageUrl(DRIVE_IDS.ac09),
    label: '솜이',
    alt: '솜이 친구',
    naturalWidth: 400,
    naturalHeight: 400,
    ring: 'border-sky-100',
    glow: 'shadow-sky-100/60',
  },
  ac10: {
    src: driveImageUrl(DRIVE_IDS.ac10),
    label: 'K.K.',
    alt: 'K.K. 친구',
    naturalWidth: 400,
    naturalHeight: 400,
    ring: 'border-blue-100',
    glow: 'shadow-blue-100/60',
  },
  ac11: {
    src: driveImageUrl(DRIVE_IDS.ac11),
    label: '린크',
    alt: '린크 친구',
    naturalWidth: 400,
    naturalHeight: 400,
    ring: 'border-indigo-100',
    glow: 'shadow-indigo-100/60',
  },
  ac12: {
    src: driveImageUrl(DRIVE_IDS.ac12),
    label: '파이프',
    alt: '파이프 친구',
    naturalWidth: 400,
    naturalHeight: 400,
    ring: 'border-violet-100',
    glow: 'shadow-violet-100/60',
  },
  ac13: {
    src: driveImageUrl(DRIVE_IDS.ac13),
    label: '카로틴',
    alt: '카로틴 친구',
    naturalWidth: 400,
    naturalHeight: 400,
    ring: 'border-purple-100',
    glow: 'shadow-purple-100/60',
  },
  ac14: {
    src: driveImageUrl(DRIVE_IDS.ac14),
    label: '핀틱',
    alt: '핀틱 친구',
    naturalWidth: 400,
    naturalHeight: 400,
    ring: 'border-fuchsia-100',
    glow: 'shadow-fuchsia-100/60',
  },
  ac15: {
    src: driveImageUrl(DRIVE_IDS.ac15),
    label: '센트엘로',
    alt: '센트엘로 친구',
    naturalWidth: 400,
    naturalHeight: 400,
    ring: 'border-pink-100',
    glow: 'shadow-pink-100/60',
  },
  ac16: {
    src: driveImageUrl(DRIVE_IDS.ac16),
    label: '요비',
    alt: '요비 친구',
    naturalWidth: 400,
    naturalHeight: 400,
    ring: 'border-stone-100',
    glow: 'shadow-stone-100/60',
  },
  ac17: {
    src: driveImageUrl(DRIVE_IDS.ac17),
    label: '명고',
    alt: '명고 친구',
    naturalWidth: 400,
    naturalHeight: 400,
    ring: 'border-slate-100',
    glow: 'shadow-slate-100/60',
  },
  ac18: {
    src: driveImageUrl(DRIVE_IDS.ac18),
    label: '그리미',
    alt: '그리미 친구',
    naturalWidth: 400,
    naturalHeight: 400,
    ring: 'border-zinc-100',
    glow: 'shadow-zinc-100/60',
  },
  ac19: {
    src: driveImageUrl(DRIVE_IDS.ac19),
    label: '체리',
    alt: '체리 친구',
    naturalWidth: 400,
    naturalHeight: 400,
    ring: 'border-neutral-100',
    glow: 'shadow-neutral-100/60',
  },
  ac20: {
    src: driveImageUrl(DRIVE_IDS.ac20),
    label: '핑키',
    alt: '핑키 친구',
    naturalWidth: 400,
    naturalHeight: 400,
    ring: 'border-red-100',
    glow: 'shadow-red-100/60',
  },
  ac21: {
    src: driveImageUrl(DRIVE_IDS.ac21),
    label: '모니카',
    alt: '모니카 친구',
    naturalWidth: 400,
    naturalHeight: 400,
    ring: 'border-rose-100',
    glow: 'shadow-rose-100/60',
  },
  ac22: {
    src: driveImageUrl(DRIVE_IDS.ac22),
    label: '글루민',
    alt: '글루민 친구',
    naturalWidth: 400,
    naturalHeight: 400,
    ring: 'border-orange-100',
    glow: 'shadow-orange-100/60',
  },
  ac23: {
    src: driveImageUrl(DRIVE_IDS.ac23),
    label: '2호',
    alt: '2호 친구',
    naturalWidth: 400,
    naturalHeight: 400,
    ring: 'border-amber-100',
    glow: 'shadow-amber-100/60',
  },
  ac24: {
    src: driveImageUrl(DRIVE_IDS.ac24),
    label: '아세로라',
    alt: '아세로라 친구',
    naturalWidth: 400,
    naturalHeight: 400,
    ring: 'border-yellow-100',
    glow: 'shadow-yellow-100/60',
  },
  ac25: {
    src: driveImageUrl(DRIVE_IDS.ac25),
    label: '부케',
    alt: '부케 친구',
    naturalWidth: 400,
    naturalHeight: 400,
    ring: 'border-lime-100',
    glow: 'shadow-lime-100/60',
  },
  ac26: {
    src: driveImageUrl(DRIVE_IDS.ac26),
    label: '연유',
    alt: '연유 친구',
    naturalWidth: 400,
    naturalHeight: 400,
    ring: 'border-emerald-100',
    glow: 'shadow-emerald-100/60',
  },
  ac27: {
    src: driveImageUrl(DRIVE_IDS.ac27),
    label: '링링',
    alt: '링링 친구',
    naturalWidth: 400,
    naturalHeight: 400,
    ring: 'border-teal-100',
    glow: 'shadow-teal-100/60',
  },
  ac28: {
    src: driveImageUrl(DRIVE_IDS.ac28),
    label: '유네찌',
    alt: '유네찌 친구',
    naturalWidth: 400,
    naturalHeight: 400,
    ring: 'border-cyan-100',
    glow: 'shadow-cyan-100/60',
  },
  ac29: {
    src: driveImageUrl(DRIVE_IDS.ac29),
    label: '메링',
    alt: '메링 친구',
    naturalWidth: 400,
    naturalHeight: 400,
    ring: 'border-sky-100',
    glow: 'shadow-sky-100/60',
  },
  ac30: {
    src: driveImageUrl(DRIVE_IDS.ac30),
    label: '백프로',
    alt: '백프로 친구',
    naturalWidth: 400,
    naturalHeight: 400,
    ring: 'border-blue-100',
    glow: 'shadow-blue-100/60',
  },
  ac31: {
    src: driveImageUrl(DRIVE_IDS.ac31),
    label: '호냥이',
    alt: '호냥이 친구',
    naturalWidth: 400,
    naturalHeight: 400,
    ring: 'border-indigo-100',
    glow: 'shadow-indigo-100/60',
  },
  ac32: {
    src: driveImageUrl(DRIVE_IDS.ac32),
    label: '델리',
    alt: '델리 친구',
    naturalWidth: 400,
    naturalHeight: 400,
    ring: 'border-violet-100',
    glow: 'shadow-violet-100/60',
  },
  ac33: {
    src: driveImageUrl(DRIVE_IDS.ac33),
    label: '패트라',
    alt: '패트라 친구',
    naturalWidth: 400,
    naturalHeight: 400,
    ring: 'border-purple-100',
    glow: 'shadow-purple-100/60',
  },
  ac34: {
    src: driveImageUrl(DRIVE_IDS.ac34),
    label: '마롱이',
    alt: '마롱이 친구',
    naturalWidth: 400,
    naturalHeight: 400,
    ring: 'border-fuchsia-100',
    glow: 'shadow-fuchsia-100/60',
  },
  ac35: {
    src: driveImageUrl(DRIVE_IDS.ac35),
    label: '빅희',
    alt: '빅희 친구',
    naturalWidth: 400,
    naturalHeight: 400,
    ring: 'border-pink-100',
    glow: 'shadow-pink-100/60',
  },
  ac36: {
    src: driveImageUrl(DRIVE_IDS.ac36),
    label: '베리',
    alt: '베리 친구',
    naturalWidth: 400,
    naturalHeight: 400,
    ring: 'border-stone-100',
    glow: 'shadow-stone-100/60',
  },
  ac37: {
    src: driveImageUrl(DRIVE_IDS.ac37),
    label: '마롱',
    alt: '마롱 친구',
    naturalWidth: 400,
    naturalHeight: 400,
    ring: 'border-slate-100',
    glow: 'shadow-slate-100/60',
  },
  ac38: {
    src: driveImageUrl(DRIVE_IDS.ac38),
    label: '가위',
    alt: '가위 친구',
    naturalWidth: 400,
    naturalHeight: 400,
    ring: 'border-zinc-100',
    glow: 'shadow-zinc-100/60',
  },
  ac39: {
    src: driveImageUrl(DRIVE_IDS.ac39),
    label: '애플',
    alt: '애플 친구',
    naturalWidth: 400,
    naturalHeight: 400,
    ring: 'border-neutral-100',
    glow: 'shadow-neutral-100/60',
  },
  ac40: {
    src: driveImageUrl(DRIVE_IDS.ac40),
    label: '크리미',
    alt: '크리미 친구',
    naturalWidth: 400,
    naturalHeight: 400,
    ring: 'border-red-100',
    glow: 'shadow-red-100/60',
  },
  ac41: {
    src: driveImageUrl(DRIVE_IDS.ac41),
    label: '루주',
    alt: '루주 친구',
    naturalWidth: 400,
    naturalHeight: 400,
    ring: 'border-rose-100',
    glow: 'shadow-rose-100/60',
  },
  ac42: {
    src: driveImageUrl(DRIVE_IDS.ac42),
    label: '차코',
    alt: '차코 친구',
    naturalWidth: 400,
    naturalHeight: 400,
    ring: 'border-orange-100',
    glow: 'shadow-orange-100/60',
  },
  ac43: {
    src: driveImageUrl(DRIVE_IDS.ac43),
    label: '크리스틴',
    alt: '크리스틴 친구',
    naturalWidth: 400,
    naturalHeight: 400,
    ring: 'border-amber-100',
    glow: 'shadow-amber-100/60',
  },
  ac44: {
    src: driveImageUrl(DRIVE_IDS.ac44),
    label: '세바',
    alt: '세바 친구',
    naturalWidth: 400,
    naturalHeight: 400,
    ring: 'border-yellow-100',
    glow: 'shadow-yellow-100/60',
  },
  ac45: {
    src: driveImageUrl(DRIVE_IDS.ac45),
    label: '린타',
    alt: '린타 친구',
    naturalWidth: 400,
    naturalHeight: 400,
    ring: 'border-lime-100',
    glow: 'shadow-lime-100/60',
  },
  ac46: {
    src: driveImageUrl(DRIVE_IDS.ac46),
    label: '릴리안',
    alt: '릴리안 친구',
    naturalWidth: 400,
    naturalHeight: 400,
    ring: 'border-emerald-100',
    glow: 'shadow-emerald-100/60',
  },
  ac47: {
    src: driveImageUrl(DRIVE_IDS.ac47),
    label: '미미',
    alt: '미미 친구',
    naturalWidth: 400,
    naturalHeight: 400,
    ring: 'border-teal-100',
    glow: 'shadow-teal-100/60',
  },
  ac48: {
    src: driveImageUrl(DRIVE_IDS.ac48),
    label: '초코',
    alt: '초코 친구',
    naturalWidth: 400,
    naturalHeight: 400,
    ring: 'border-cyan-100',
    glow: 'shadow-cyan-100/60',
  },
  ac49: {
    src: driveImageUrl(DRIVE_IDS.ac49),
    label: '패티카',
    alt: '패티카 친구',
    naturalWidth: 400,
    naturalHeight: 400,
    ring: 'border-sky-100',
    glow: 'shadow-sky-100/60',
  },
  ac50: {
    src: driveImageUrl(DRIVE_IDS.ac50),
    label: '루나',
    alt: '루나 친구',
    naturalWidth: 400,
    naturalHeight: 400,
    ring: 'border-blue-100',
    glow: 'shadow-blue-100/60',
  },
  ac51: {
    src: driveImageUrl(DRIVE_IDS.ac51),
    label: '피카',
    alt: '피카 친구',
    naturalWidth: 400,
    naturalHeight: 400,
    ring: 'border-indigo-100',
    glow: 'shadow-indigo-100/60',
  },
  ac52: {
    src: driveImageUrl(DRIVE_IDS.ac52),
    label: '플라라',
    alt: '플라라 친구',
    naturalWidth: 400,
    naturalHeight: 400,
    ring: 'border-violet-100',
    glow: 'shadow-violet-100/60',
  },
  ac53: {
    src: driveImageUrl(DRIVE_IDS.ac53),
    label: '데자네',
    alt: '데자네 친구',
    naturalWidth: 400,
    naturalHeight: 400,
    ring: 'border-purple-100',
    glow: 'shadow-purple-100/60',
  },
  ac54: {
    src: driveImageUrl(DRIVE_IDS.ac54),
    label: '사탕',
    alt: '사탕 친구',
    naturalWidth: 400,
    naturalHeight: 400,
    ring: 'border-fuchsia-100',
    glow: 'shadow-fuchsia-100/60',
  },
  ac55: {
    src: driveImageUrl(DRIVE_IDS.ac55),
    label: '란자나',
    alt: '란자나 친구',
    naturalWidth: 400,
    naturalHeight: 400,
    ring: 'border-pink-100',
    glow: 'shadow-pink-100/60',
  },
  ac56: {
    src: driveImageUrl(DRIVE_IDS.ac56),
    label: '찍순이',
    alt: '찍순이 친구',
    naturalWidth: 400,
    naturalHeight: 400,
    ring: 'border-stone-100',
    glow: 'shadow-stone-100/60',
  },
  ac57: {
    src: driveImageUrl(DRIVE_IDS.ac57),
    label: '미자벨',
    alt: '미자벨 친구',
    naturalWidth: 400,
    naturalHeight: 400,
    ring: 'border-slate-100',
    glow: 'shadow-slate-100/60',
  },
  ac58: {
    src: driveImageUrl(DRIVE_IDS.ac58),
    label: '고북',
    alt: '고북 친구',
    naturalWidth: 400,
    naturalHeight: 400,
    ring: 'border-zinc-100',
    glow: 'shadow-zinc-100/60',
  },
  ac59: {
    src: driveImageUrl(DRIVE_IDS.ac59),
    label: '사하라',
    alt: '사하라 친구',
    naturalWidth: 400,
    naturalHeight: 400,
    ring: 'border-neutral-100',
    glow: 'shadow-neutral-100/60',
  },
  ac60: {
    src: driveImageUrl(DRIVE_IDS.ac60),
    label: '카트리나',
    alt: '카트리나 친구',
    naturalWidth: 400,
    naturalHeight: 400,
    ring: 'border-red-100',
    glow: 'shadow-red-100/60',
  },
  ac61: {
    src: driveImageUrl(DRIVE_IDS.ac61),
    label: '몽세르',
    alt: '몽세르 친구',
    naturalWidth: 400,
    naturalHeight: 400,
    ring: 'border-rose-100',
    glow: 'shadow-rose-100/60',
  },
  ac62: {
    src: driveImageUrl(DRIVE_IDS.ac62),
    label: '여욱',
    alt: '여욱 친구',
    naturalWidth: 400,
    naturalHeight: 400,
    ring: 'border-orange-100',
    glow: 'shadow-orange-100/60',
  },
  ac63: {
    src: driveImageUrl(DRIVE_IDS.ac63),
    label: '갑돌',
    alt: '갑돌 친구',
    naturalWidth: 400,
    naturalHeight: 400,
    ring: 'border-amber-100',
    glow: 'shadow-amber-100/60',
  },
  ac64: {
    src: driveImageUrl(DRIVE_IDS.ac64),
    label: '해탈한',
    alt: '해탈한 친구',
    naturalWidth: 400,
    naturalHeight: 400,
    ring: 'border-yellow-100',
    glow: 'shadow-yellow-100/60',
  },
  ac65: {
    src: driveImageUrl(DRIVE_IDS.ac65),
    label: '콩돌이',
    alt: '콩돌이 친구',
    naturalWidth: 400,
    naturalHeight: 400,
    ring: 'border-lime-100',
    glow: 'shadow-lime-100/60',
  },
  ac66: {
    src: driveImageUrl(DRIVE_IDS.ac66),
    label: '고옥이',
    alt: '고옥이 친구',
    naturalWidth: 400,
    naturalHeight: 400,
    ring: 'border-emerald-100',
    glow: 'shadow-emerald-100/60',
  },
  ac67: {
    src: driveImageUrl(DRIVE_IDS.ac67),
    label: '너굴',
    alt: '너굴 친구',
    naturalWidth: 400,
    naturalHeight: 400,
    ring: 'border-teal-100',
    glow: 'shadow-teal-100/60',
  },
  ac68: {
    src: driveImageUrl(DRIVE_IDS.ac68),
    label: 'DJ K.K.',
    alt: 'DJ K.K. 친구',
    naturalWidth: 400,
    naturalHeight: 400,
    ring: 'border-cyan-100',
    glow: 'shadow-cyan-100/60',
  },
  ac69: {
    src: driveImageUrl(DRIVE_IDS.ac69),
    label: '여울',
    alt: '여울 친구',
    naturalWidth: 400,
    naturalHeight: 400,
    ring: 'border-sky-100',
    glow: 'shadow-sky-100/60',
  },
};

export const CHARACTER_NAMES = Object.keys(CHARACTERS);
